name: wekil_ai_mobile_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  google_fonts: ^6.0.0
  flutter:
    sdk: flutter
  go_router: ^16.2.1
  get_it: ^8.2.0
  flutter_bloc: ^9.1.1
   
  flutter_localization: ^0.3.3
  intl: ^0.20.2     
  syncfusion_flutter_pdfviewer: ^30.2.7
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  dartz: ^0.10.1
  connectivity_plus: ^6.1.1
  http: ^1.4.0
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^9.2.4
  flutter_native_splash: ^2.4.6
  pin_code_fields: ^8.0.1
  file_picker: ^8.1.2
  signature: ^6.3.0
  dotted_border: ^2.1.0
  video_player: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.5.0
  build_runner: ^2.4.7
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  flutter_launcher_icons: ^0.14.4
flutter:
  uses-material-design: true
  assets:
  - assets/splash/loader.gif.mp4
  - assets/splash/logo.jpg
  fonts:
    - family: NotoSansEthiopic
      fonts:
        - asset: assets/fonts/NotoSansEthiopic-Regular.ttf
        - asset: assets/fonts/NotoSansEthiopic-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_28pt-Regular.ttf
        - asset: assets/fonts/Inter_28pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter_28pt-Bold.ttf
          weight: 700

flutter_native_splash:
  image: assets/splash/logo.jpg
  color: "#ffffff"
  ios_content_mode: scaleAspectFit
  android_gravity: center
  android_12:
    color: "#ffffff"
    icon_background_color: "#ffffff"
    image: assets/splash/logo.jpg
  fullscreen: true

# App launcher icons configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/splash/logo.jpg
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/splash/logo.jpg
  min_sdk_android: 21

